/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SWING;

import DAO.DichVuDAO;
import HELPER.DateHelper;
import HELPER.DialogHelper;
import HELPER.ShareHelper;
import MODEL.DichVu;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DuongNVPH
 */
public class MainFrame extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        btnLichHen = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnDichVu = new javax.swing.JButton();
        btnLuong = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        lblNguoiDangNhap = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        mnuTroGiup_mniHuongDanSuDung = new javax.swing.JMenuItem();
        mnuTroGiup_mniGioiThieuSanPham = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnHoaDon.setBackground(new java.awt.Color(0, 0, 255));
        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.setPreferredSize(new java.awt.Dimension(187, 23));
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        jPanel2.add(btnHoaDon);

        btnLichHen.setBackground(new java.awt.Color(0, 0, 255));
        btnLichHen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLichHen.setForeground(new java.awt.Color(255, 255, 255));
        btnLichHen.setText("LỊCH HẸN");
        btnLichHen.setPreferredSize(new java.awt.Dimension(187, 23));
        btnLichHen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLichHenActionPerformed(evt);
            }
        });
        jPanel2.add(btnLichHen);

        btnKhachHang.setBackground(new java.awt.Color(0, 0, 255));
        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");
        btnKhachHang.setPreferredSize(new java.awt.Dimension(187, 23));
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jPanel2.add(btnKhachHang);

        btnDichVu.setBackground(new java.awt.Color(0, 0, 255));
        btnDichVu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDichVu.setForeground(new java.awt.Color(255, 255, 255));
        btnDichVu.setText("DỊCH VỤ");
        btnDichVu.setPreferredSize(new java.awt.Dimension(187, 23));
        btnDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDichVuActionPerformed(evt);
            }
        });
        jPanel2.add(btnDichVu);

        btnLuong.setBackground(new java.awt.Color(0, 0, 255));
        btnLuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLuong.setForeground(new java.awt.Color(255, 255, 255));
        btnLuong.setText("LƯƠNG");
        btnLuong.setPreferredSize(new java.awt.Dimension(187, 23));
        btnLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongActionPerformed(evt);
            }
        });
        jPanel2.add(btnLuong);

        btnThoat.setBackground(new java.awt.Color(0, 0, 255));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnThoat);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));

        pnlMain.setLayout(new java.awt.CardLayout());
        jPanel1.add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 1340, 600));

        lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 657, 200, 20));
        jPanel1.add(lblNguoiDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 657, 244, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1340, 10));

        jMenu3.setText("Hệ thống");

        jMenuItem1.setText("Đăng Xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Đổi Mật Khẩu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Kết Thúc Chương Trình");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Quản lý");

        jMenu1.setText("jMenu1");
        jMenu4.add(jMenu1);

        jMenu2.setText("jMenu2");
        jMenu4.add(jMenu2);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Thống kê");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Trợ giúp");

        mnuTroGiup_mniHuongDanSuDung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mnuTroGiup_mniHuongDanSuDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Globe.png"))); // NOI18N
        mnuTroGiup_mniHuongDanSuDung.setText("Hướng dẫn sử dụng");
        mnuTroGiup_mniHuongDanSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTroGiup_mniHuongDanSuDungActionPerformed(evt);
            }
        });
        jMenu6.add(mnuTroGiup_mniHuongDanSuDung);

        mnuTroGiup_mniGioiThieuSanPham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnuTroGiup_mniGioiThieuSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/Home.png"))); // NOI18N
        mnuTroGiup_mniGioiThieuSanPham.setText("Giới thiệu sản phẩm");
        mnuTroGiup_mniGioiThieuSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTroGiup_mniGioiThieuSanPhamActionPerformed(evt);
            }
        });
        jMenu6.add(mnuTroGiup_mniGioiThieuSanPham);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
        openQuanLyKhachHang();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        openQuanLyHoaDon();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnLichHenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichHenActionPerformed
        // TODO add your handling code here:
        openLichHen();
    }//GEN-LAST:event_btnLichHenActionPerformed

    private void btnDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDichVuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDichVuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnThoatActionPerformed

    private void mnuTroGiup_mniHuongDanSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTroGiup_mniHuongDanSuDungActionPerformed

    }//GEN-LAST:event_mnuTroGiup_mniHuongDanSuDungActionPerformed

    private void mnuTroGiup_mniGioiThieuSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTroGiup_mniGioiThieuSanPhamActionPerformed

    }//GEN-LAST:event_mnuTroGiup_mniGioiThieuSanPhamActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new QuenMatKhauJDialog(this,true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (DialogHelper.confirm(this, "Bạn có muốn thoát chương trình ?")) {
            System.exit(0);
        }
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        openDangXuat();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLuongActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDichVu;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLichHen;
    private javax.swing.JButton btnLuong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblNguoiDangNhap;
    private javax.swing.JMenuItem mnuTroGiup_mniGioiThieuSanPham;
    private javax.swing.JMenuItem mnuTroGiup_mniHuongDanSuDung;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
    DichVuDAO dvdao = new DichVuDAO();
    
    void init(){
        setLocationRelativeTo(null);
        Thread t = new Thread(this);
        t.start();
        openLogin();
        if (ShareHelper.isManager()) {
            btnDichVu.setEnabled(true);
            btnLuong.setEnabled(true);
        }else{
            btnLuong.setEnabled(false);
            btnDichVu.setEnabled(false);
        }
    }
    
    void openLogin(){
        if (ShareHelper.isLogin()) {
            this.setVisible(true);
            lblNguoiDangNhap.setText(ShareHelper.user.getTenDangNhap());
        }else{
            new DangNhapJDialog(this, true).setVisible(true);
        }
    }
    void openDangXuat(){
        ShareHelper.clear();
        new DangNhapJDialog(this, true).setVisible(true);
    }
    
    void openQuanLyHoaDon(){
        QuanLyHoaDonPanel qlhd = new QuanLyHoaDonPanel();
        pnlMain.add(qlhd,"QuanLyHoaDon");
        CardLayout car = (CardLayout) pnlMain.getLayout();
        car.show(pnlMain, "QuanLyHoaDon");
    }
    void openLichHen(){
        QuanLyLichDatPanel lichDat = new QuanLyLichDatPanel();
        pnlMain.add(lichDat,"LichDat");
        CardLayout car = (CardLayout) pnlMain.getLayout();
        car.show(pnlMain, "LichDat");
    }
    
    void openQuanLyKhachHang(){
        QuanLyKhachHangPanel khachHang = new QuanLyKhachHangPanel();
        pnlMain.add(khachHang,"KhachHang");
        CardLayout car = (CardLayout) pnlMain.getLayout();
        car.show(pnlMain, "KhachHang");
    }
    @Override
    public void run() {
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
        while (true) {            
            lblDongHo.setText(sdf.format(new Date()));
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    
    }
   
